### ISSUE TITLE
Changes from most to least impactful 

### ISSUE THREAD

**Issue by John-R-Wallace-NOAA** [shcaba/Natural-Mortality-Tool#12]
- For the call to FishLife() , add mfrow = c(2,2).  This makes it so the you can see the y-axis label and see what is being plotted against what in each of the figures:
     spp_info <- try(FishLife::Plot_taxa(FishLife::Search_species(Genus=genus, Species=species)$match_taxonomy, mfrow = c(2,2)))

- In output$Mtable2 <- renderTable(...) you no longer need:
  User_M<-input$User_M  
since User_M is now dealt with in  output$MtableUser <- renderTable(...)

- "Approximate the density (spelled denisty) function" 'f' is created but not used:
     f <- approxfun(M.densum$x, M.densum$y, yleft=0, yright=0

- Having the weighting for User_M be just UserM  and not, e.g. UserM_wt, was confusing.

- You no longer need the wrapper shinyServer() nor shinyUI() as of Shiny 0.10, see the help for each.

- You don't explicitly explain that if one wants an entire group to be down-weighted what is course of action. Is it possible to reduce each member by that value?  Continuing your example, if one wants the entire Amax group to be down-weighted by 0.5 compared to the other methods, then would reducing each 0.25 by 0.5 work or not.

Great tool :-)

**Comment by shcaba** [comment]
Thanks you John for taking a look and getting me some feedback.
Some of these issues are on my things to do list, but others are not. 
I will work on these suggestions, and likely bug you about them.
